spring:
  application:
    name: emp-service
  datasource:
   url: jdbc:mysql://localhost:3306/springdb
   username: ${DB_USER:root}
   password: ${DB_PASSWORD:P@ssword}
   hikari:
      connection-init-sql: select count(empno) from myemp;
      minimum-idle: 5
      initialization-fail-timeout: 1
  jpa:
     show_sql: true
     hibernate:
      ddl-auto: update
  cache:
    type: simple
  security:
   oauth2:
    resourceserver:
     jwt:
       issuer-uri: http://localhost:8080/realms/myrealm
       jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
logging:
  level:
    '[org.springframework.jdbc]': debug
    '[org.springframework.cache]': debug
    #'[org.hibernate.orm]': debug

resilience4j:
  circuitbreaker:
    instances:
     emp-cb:
       registerHealthIndicator: true
       slidingWindowSize: 10
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowType: COUNT_BASED
       minimumNumberOfCalls: 2
       waitDurationInOpenState: 10s
       failureRateThreshold: 33.3
       automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      emp-retry:
       maxAttempts: 3
       wait-duration: 500ms
       fail-after-max-attempts: true
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health: 
   circuitbreakers:
      enabled: true
  observations:
    annotations:
      enabled: true
  tracing:
    export:
      enabled: true
     # zipkin:
       # enabled: true
    sampling:
      probability: 1.0

app:
 datasource:
  mysql:
   url: jdbc:mysql://localhost:3306/springdb
   username: root
   password: P@ssword
   


    